Added new site and refactored to use __MODULE__ constant
lawik/beambloggers pull request #13
Opened 2020-11-20 07:12 UTC by venomnert

2020-11-20 07:14 UTC, venomnert commented
Added todo

2020-11-20 07:52 UTC, lawik requested changes
The changes suggestions are much appreciated. I found one regression in the application behavior that I don't want to introduce. It'll be in the review comments :)

2020-11-20 07:52 UTC, lawik commented on lib/webring/site.ex
> +      Enum.reduce(site, %__MODULE__{}, fn {key, value}, site ->
In this particular case I would just use the `%Site{}` statement because it gives more information in the local context and is more clear to read in my opinion.

2020-11-20 07:52 UTC, lawik commented on lib/webring/fair_chance.ex
> +    GenServer.start_link(__MODULE__, nil, name: __MODULE__)
Good cleanup

2020-11-20 07:52 UTC, lawik commented on lib/webring/site.ex
> +  end
This is not an equivalent change.

A dirty little trick of putting this in module attributes is that this reads and parses the site data at compile-time. The list becomes static and as such incredibly fast whenever the application needs to fetch the list of sites.

It gets tricky to use the functions inside this module that aren't compiled yet and that's why that module attribute is ugly. We could likely break those functions out to another module to clean things up.

I want to keep the sites being read and packaged up at compile time since that saves on IO and provides performance.

Let me know if you have questions on how this works.

2020-11-20 07:52 UTC, lawik commented on priv/sites/nert.txt
> +http://goodjam.blog/
If you want the blog to get in before the rest of the code changes you are free to split it off into a separate PR :)

2020-11-21 00:00 UTC, venomnert commented on lib/webring/site.ex
> +      Enum.reduce(site, %__MODULE__{}, fn {key, value}, site ->
Agreed.

2020-11-21 00:02 UTC, venomnert commented on lib/webring/site.ex
> +  end
I would like to know more about this.

2020-11-23 07:44 UTC, lawik commented on priv/sites/nert.txt
> +http://goodjam.blog/
Easiest thing is probably:

- Save this file off to the side, so you don't have to retype it
- Clean up your forked repo with something like this: https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream (this will kill your other changes as they are in the master branch), you can also delete your fork on github and fork again
- Re-add the site stuff but do it in a branch
- Send PR for that branch into lawik:master

The good part about being on a separate branch is that if you need to do more stuff from your master you won't have to reset to the my master, you can just discard the branch. And your master can be updated to match the original master whenever needed.

2020-11-23 07:51 UTC, lawik commented on lib/webring/site.ex
> +  end
Okay, I'll try to explain. You can try this post as well which does something similar: https://underjord.io/a-slight-delight-compile-time-checking.html

Elixir/Erlang, etc, all run code at essentially two stages. At compile-time, that's when Macros run and modules and functions in your files become defined. This all gets translated to the BEAM virtual machine code that can run later. This code we wrote gets interpreted and run at run-time by the BEAM virtual machine.

So compile-time stuff is done when you package up your application and run-time stuff is done whenever that code-path is hit by your user.

In this case we are using a module attribute which is part of the module definition. And that is resolved into values at compile-time. This means that the list of sites is turned into the BEAM code once, at compile-time. And then when I put this on the server the list of sites is as tightly wired into the code as the function definitions and modules.

The way you tried to clean it up would move it to being called at runtime. It would still be fairly fast, but it would need to look at the disk to list the files, read and parse each file and determine if they are valid, etc. everytime someone wants to view the list of sites. But the list of sites only changes when the repo is updated. So I want it to only be updated at compile-time.

Did that clear things up a bit?

2020-11-25 14:45 UTC, lawik commented
I will close this PR. If you want to do a similar piece of refactor its fine to start a new PR but this is slipping out of date.

2020-11-25 14:45 UTC, closed without merging